Meus estudos
GabrielRozendo/Estudos pull request #2
Opened 2020-03-31 18:42 UTC by PeterCcT

2020-03-31 21:51 UTC, GabrielRozendo requested changes

2020-03-31 21:51 UTC, GabrielRozendo commented on lib/classes/atleta/atleta.dart
> +  Atleta(String nome,int idade,double peso,String cpf,String assinatura,this._modalidade)
Atleta(String nome....) : super(this.nome);

2020-03-31 21:51 UTC, GabrielRozendo commented on lib/classes/atleta/atleta.dart
> +  Atleta(String nome,int idade,double peso,String cpf,String assinatura,this._modalidade)
_modalidade => modalidade
this.modalidade

2020-03-31 21:51 UTC, GabrielRozendo commented on lib/classes/atleta/atleta.dart
> +        "O atleta $nome comeu e ganhou ${_pesoGanho(calorias)}! E agora esta com ${peso}Kg");
_pesoGanho(calorias)

2020-03-31 21:51 UTC, GabrielRozendo commented on lib/classes/atleta/atleta.dart
> +        "O atleta $nome comeu e ganhou ${_pesoGanho(calorias)}! E agora esta com ${peso}Kg");
Final double pesoGanho = _pesoGanho(calorias);
print('....$pesoGanho');

2020-03-31 21:51 UTC, GabrielRozendo commented on lib/classes/atleta/atleta.dart
> +      this._peso += calorias;
this._peso += calorias;

2020-03-31 21:51 UTC, GabrielRozendo commented on lib/classes/atleta/atleta.dart
> +    if (calorias > 1 || calorias == 1) {
calorias >= 1

2020-03-31 21:51 UTC, GabrielRozendo commented on lib/classes/atleta/atleta.dart
> +  String listarDados() {
dica: vc pode dar um override no toString da classe e imprimir isso, vai ficar top e mais legal :-)

2020-03-31 21:51 UTC, GabrielRozendo commented on lib/classes/time/time.dart
> +      return this._atletas.forEach((item) => print(item.listarDados()));
aí vc nem precisaria chamar o listarDados, só o print do item ele já iria lá no toString() q vc criou :-) 
mas se vc forçar o item.toString() tb seria mesma coisa

2020-03-31 21:51 UTC, GabrielRozendo commented on lib/classes/time/time.dart
> +
olha o format faltando aqui

2020-03-31 21:51 UTC, GabrielRozendo commented on lib/classes/time/time.dart
> +    this._atletas.removeWhere((atletas) => atleta.cpf == atletas.cpf);
removeWhere booaaaaaa =)

2020-04-01 20:47 UTC, GabrielRozendo requested changes

2020-04-01 20:47 UTC, GabrielRozendo commented on lib/classes/Texto/Texto.dart
> +  static String gastoAprovadotxt(String nome, double dinheiro, salario) {
salario é de q tipo?
dynamic mesmo?

2020-04-01 20:47 UTC, GabrielRozendo commented on lib/classes/atleta/atleta.dart
> +import"lib/classes/pessoa/pessoa.dart";
coloca um espaço depois do import 👎

2020-04-01 20:47 UTC, GabrielRozendo commented on lib/classes/atleta/atleta.dart
> +  get tipo => this._modalidade;
falamos disso, lembra?

2020-04-01 20:47 UTC, GabrielRozendo commented on lib/classes/atleta/atleta.dart
> +  set modalidade(String modalidade) => this._modalidade = modalidade;
String modalidade

2020-04-01 20:47 UTC, GabrielRozendo commented on lib/classes/atleta/atleta.dart
> +      this._peso -= calorias;
se essa linha vai acontecer dentro do if e do else, logo ela tem q acontecer de todo jeito, logo pode ficar fora do if/else e evitar de repetir na linha 37

2020-04-01 20:47 UTC, GabrielRozendo commented on lib/classes/diretor/diretor.dart
> +    atleta.contrato = Contrato(tipo,termos,valor,dtinicio,dtfinal,atleta.assinar(),this.assinar());
usa a formatação default do VSCode que ele já ajusta aí pra gente

2020-04-01 20:47 UTC, GabrielRozendo commented on lib/classes/pessoa/pessoa.dart
> +  set nome(String nome) => this._nome = nome;
final String nome;
e ranca isso

2020-04-01 20:47 UTC, GabrielRozendo commented on lib/classes/planejamentoT/planejamentoT.dart
> +class PlanejamentoTreino {
o nome do arquivo é planejamentoT e o nome da classe PlanjamentoTreino.
Renomeia o nome do arquivo pra ficar igual o da classe

2020-04-01 20:47 UTC, GabrielRozendo commented on lib/classes/planejamentoT/planejamentoT.dart
> +  String _instrucoes;
final?

2020-04-01 20:47 UTC, GabrielRozendo commented on lib/classes/tecnico/tecnico.dart
> +    }
e se ficasse assim, qual a diferença?
return idade >= 18 && peso > 60;

2020-04-01 20:47 UTC, GabrielRozendo commented on lib/classes/time/time.dart
> +  Tecnico _tecnico;
quais dessas podem ser final?

2020-04-01 20:47 UTC, GabrielRozendo commented on lib/classes/time/time.dart
> +  String _nome, _cnpj;
Evita colocar mais de uma variavel na mesma linha, fica mais dificil de ler/achar depois

2020-04-01 20:47 UTC, GabrielRozendo commented on lib/classes/time/time.dart
> +  }
mais elegante assim =)

PlanejamentoTreino get _obterTreino => this._tecnico.treino;

2020-04-01 20:47 UTC, GabrielRozendo commented on lib/classes/time/time.dart
> +    if (_obterTreino().instrucoes != "" && this._tecnico.assinatura == _obterTreino().assinatura) {
aquele mesmo caso, quebra isso antes do if...

vc pode criar inclusive assim:
_obterTreino().instrucoes.isEmpty
(algo do tipo no dart)

2020-04-01 20:47 UTC, GabrielRozendo commented on lib/main.dart
> +
format no arquivo...
olha o monte de texto junto, isso é horrivel pra ler depois
olha o monte de linha em branco

2020-04-03 14:48 UTC, GabrielRozendo requested changes

2020-04-03 14:48 UTC, GabrielRozendo commented on lib/classes/Texto.dart
> +}
repara que ele mesmo já detecta um erro no arquiv, que é faltando uma última linha ali...
se vc formatar o arquivo já resolve pra vc, inclusive outros espaçamentos faltando ali...

2020-04-03 14:48 UTC, GabrielRozendo commented on lib/classes/atleta.dart
> +
duas linhas consecutivas, problema de formatação do arquivo :-)

2020-04-03 14:48 UTC, GabrielRozendo commented on lib/classes/atleta.dart
> +  Atleta(String nome,int idade,double peso,String cpf,String assinatura,this.modalidade):super(nome,idade,peso,cpf,assinatura);
cadê os espaços entre as virgulas? fica horrível de ler...

problema q seria facilmente resolvido com a formatação do arquivo :-)

2020-04-03 14:48 UTC, GabrielRozendo commented on lib/classes/atleta.dart
> +  get contrato => this._contrato;
pra q encapsular nesse caso então?

2020-04-03 14:48 UTC, GabrielRozendo commented on lib/classes/atleta.dart
> +
linha em branco entre o método e o comando?
problema q seria facilmente resolvido com a formatação do arquivo :-)

2020-04-03 14:48 UTC, GabrielRozendo commented on lib/classes/tecnico.dart
> +  Tecnico(String nome,int idade,double peso,String cpf,String assinatura):super(nome,idade,peso,cpf,assinatura);
cadê os espaços entre as palavras, variáveis, etc?

problema q seria facilmente resolvido com a formatação do arquivo :-)

2020-04-03 14:48 UTC, GabrielRozendo commented on lib/classes/tecnico.dart
> +    }
pq simplesmente ñ retornar o valor do "if"?
ele já é o return em si...

é tipo fazer isso:
```
bool boleana = true;
if (boleana) return true;
else return false;
```

ñ é mais fácil:
`return boleana;`
?

mesmo resultado bem mais simples

2020-04-03 14:48 UTC, GabrielRozendo commented on lib/classes/time.dart
> +import 'planejamentoT.dart';
cadê o padrão?
ou usa só ' ou só "

misturar os dois ñ dá né haha

2020-04-03 14:48 UTC, GabrielRozendo commented on lib/classes/time.dart
> +  get fundoMonetario => this._fundoMonetario;
encapsular pra q nesse caso?

2020-04-03 14:48 UTC, GabrielRozendo commented on lib/classes/time.dart
> +    if (this._tecnico.testarAtleta(atleta.idade, atleta.peso) == true) {
se o retorno é boleano, pra que já comparar com outro boleano?
```
bool resultado;
if (resultado == true)
if (resultado)
```

2020-04-03 14:48 UTC, GabrielRozendo commented on lib/main.dart
> +  Atleta ok = Atleta("Pedro", 18, 76, "121.692.176-33", "pedro", "Futsal");
' ou "

escolha um e use sempre o mesmo
cara hora um não dá...

eu particularmente to gostando mais de usar só ', mas é seu critério

2020-04-03 14:48 UTC, GabrielRozendo commented on lib/main.dart
> +  ok4.salario = 10000;
eu não sei, mas será que o salário ñ pode passar pro construtor não?

2020-04-03 17:20 UTC, GabrielRozendo requested changes

2020-04-03 17:20 UTC, GabrielRozendo commented on lib/classes/contrato.dart
> +  String listarDadosContrato() {
toString aqui :-)

2020-04-03 17:20 UTC, GabrielRozendo commented on lib/classes/time.dart
> +  void listarDaddosA() {
toString

2020-04-03 17:20 UTC, GabrielRozendo commented on lib/main.dart
> +  vasco.listarDaddosA();
print(vasco)

2020-04-03 19:22 UTC, GabrielRozendo requested changes

2020-04-03 19:22 UTC, GabrielRozendo commented on lib/classes/contrato.dart
> +  toString()
esse método vai retornar o q? é bom explicitar

2020-04-03 19:22 UTC, GabrielRozendo commented on lib/classes/pessoa.dart
> +  set idade(int idade) => this._idade = idade;
??

2020-04-03 19:22 UTC, GabrielRozendo commented on lib/classes/pessoa.dart
> +  get peso => this._peso;
ué...

2020-04-03 19:22 UTC, GabrielRozendo commented on lib/classes/pessoa.dart
> +  String assinar() => assinatura;
o get da própria assinatura já não resolve?

2020-04-03 19:22 UTC, GabrielRozendo commented on lib/classes/tecnico.dart
> +    if (idade >= 18 && peso > 60) {
esqueceu desse

2020-04-03 19:22 UTC, GabrielRozendo commented on lib/classes/time.dart
> +import "planejamentoT.dart";
repara q só um começa com a letra maiuscula haha

2020-04-03 19:22 UTC, GabrielRozendo commented on lib/classes/time.dart
> +  List _atletas = <Atleta>[];
assim fica melhor, pq senão é uma lista dinamica
`List<Atleta> _atletas = [];`

2020-04-03 19:22 UTC, GabrielRozendo commented on lib/classes/time.dart
> +    _listarDaddosA();
esse aqui ficou serviço porco hein haha

2020-04-03 20:07 UTC, PeterCcT commented on lib/classes/tecnico.dart
> +    if (idade >= 18 && peso > 60) {
Tipo,tá td certo não tá não?

2020-04-03 20:17 UTC, GabrielRozendo commented on lib/classes/tecnico.dart
> +    }
@PeterCcT olha aqui...

2020-04-03 20:17 UTC, GabrielRozendo commented on lib/classes/tecnico.dart
> +    if (idade >= 18 && peso > 60) {
certo tá, mas pode ficar melhor :-) 
olha o outro comentário q te marquei pra vc ver

2020-04-03 20:46 UTC, GabrielRozendo approved these changes

2020-04-03 20:46 UTC, GabrielRozendo commented on lib/classes/pessoa.dart
> +  get idade => this._idade;
esse ficou pra trás hein

2020-04-03 20:46 UTC, merged